services:
  - type: web
    name: NBA-Picks-Bot
    env: python
    region: virgina  # Use your preferred Render region
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
